export const categories = [
  {
    id: 1,
    name: "Pizza",
    image: require("../assets/images/pizza.jpeg"),
  },
  {
    id: 2,
    name: "Burger",
    image: require("../assets/images/pizza.jpeg"),
  },
  {
    id: 3,
    name: "Italian",
    image: require("../assets/images/pizza.jpeg"),
  },
  {
    id: 4,
    name: "Chinese",
    image: require("../assets/images/pizza.jpeg"),
  },
  {
    id: 5,
    name: "Noodles",
    image: require("../assets/images/pizza.jpeg"),
  },
  {
    id: 6,
    name: "Sweets",
    image: require("../assets/images/pizza.jpeg"),
  },
];

export const featured = [
  {
    id: 1,
    title: "Hot and Spicy",
    description: "Soft and tender fried chicken",
    restaurants: [
      {
        id: 1,
        image: require("../assets/images/avai-disc-meal2.png"),
        name: "Papa Johns",
        description: "Hot and Spicy Pizzas",
        lng: 3.379206,
        lat: 6.524379,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy.png"),
            price: 10,
          },
          {
            id: 2,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy.png"),
            price: 10,
          },
          {
            id: 3,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy.png"),
            price: 10,
          },
        ],
      },
      {
        id: 2,
        image: require("../assets/images/avai-disc-meal2.png"),
        name: "Papa Johns",
        description: "Hot and Spicy Pizzas",
        lng: 38.2145602,
        lat: -85.5324269,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy2.png"),
            price: 10,
          },
          {
            id: 2,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy2.png"),
            price: 10,
          },
          {
            id: 3,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy2.png"),
            price: 10,
          },
        ],
      },
      {
        id: 3,
        image: require("../assets/images/avai-disc-meal2.png"),
        name: "Papa Johns",
        description: "Hot and Spicy Pizzas",
        lng: 38.2145602,
        lat: -85.5324269,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/avai-disc-meal4.png"),
            price: 10,
          },
          {
            id: 2,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/avai-disc-meal4.png"),
            price: 10,
          },
          {
            id: 3,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/avai-disc-meal4.png"),
            price: 10,
          },
        ],
      },
      {
        id: 4,
        image: require("../assets/images/avai-disc-meal2.png"),
        name: "Papa Johns",
        description: "Hot and Spicy Pizzas",
        lng: 38.2145602,
        lat: -85.5324269,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/sea food.jpeg"),
            price: 10,
          },
          {
            id: 2,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/sea food.jpeg"),
            price: 10,
          },
          {
            id: 3,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/sea food.jpeg"),
            price: 10,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Sauced and Spicy",
    description: "Soft and tender fried chicken",
    restaurants: [
      {
        id: 1,
        image: require("../assets/images/avai-disc-meal2.png"),
        name: "Papa Johns",
        description: "Hot and Spicy Pizzas",
        lng: 3.379206,
        lat: 6.524379,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy.png"),
            price: 10,
          },
          {
            id: 2,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy.png"),
            price: 10,
          },
          {
            id: 3,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy.png"),
            price: 10,
          },
        ],
      },
      {
        id: 2,
        image: require("../assets/images/avai-disc-meal2.png"),
        name: "Mama Johns",
        description: "Hot and Spicy Pizzas",
        lng: 38.2145602,
        lat: -85.5324269,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy2.png"),
            price: 10,
          },
          {
            id: 2,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy2.png"),
            price: 10,
          },
          {
            id: 3,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy2.png"),
            price: 10,
          },
        ],
      },
      {
        id: 3,
        image: require("../assets/images/avai-disc-meal2.png"),
        name: "Papa Johns",
        description: "Hot and Spicy Pizzas",
        lng: 38.2145602,
        lat: -85.5324269,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/avai-disc-meal4.png"),
            price: 10,
          },
          {
            id: 2,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/avai-disc-meal4.png"),
            price: 10,
          },
          {
            id: 3,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/avai-disc-meal4.png"),
            price: 10,
          },
        ],
      },
      {
        id: 4,
        image: require("../assets/images/avai-disc-meal2.png"),
        name: "Papa Johns",
        description: "Hot and Spicy Pizzas",
        lng: 38.2145602,
        lat: -85.5324269,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/sea food.jpeg"),
            price: 10,
          },
          {
            id: 2,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/sea food.jpeg"),
            price: 10,
          },
          {
            id: 3,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/sea food.jpeg"),
            price: 10,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: "Fried and Spicy",
    description: "Soft and tender fried chicken",
    restaurants: [
      {
        id: 1,
        image: require("../assets/images/avai-disc-meal2.png"),
        name: "Papa Johns",
        description: "Hot and Spicy Pizzas",
        lng: 3.379206,
        lat: 6.524379,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy.png"),
            price: 10,
          },
          {
            id: 2,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy.png"),
            price: 10,
          },
          {
            id: 3,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy.png"),
            price: 10,
          },
        ],
      },
      {
        id: 2,
        image: require("../assets/images/avai-disc-meal2.png"),
        name: "Papa Johns",
        description: "Hot and Spicy Pizzas",
        lng: 38.2145602,
        lat: -85.5324269,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy2.png"),
            price: 10,
          },
          {
            id: 2,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy2.png"),
            price: 10,
          },
          {
            id: 3,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/allYummy2.png"),
            price: 10,
          },
        ],
      },
      {
        id: 3,
        image: require("../assets/images/avai-disc-meal2.png"),
        name: "Papa Johns",
        description: "Hot and Spicy Pizzas",
        lng: 38.2145602,
        lat: -85.5324269,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/avai-disc-meal4.png"),
            price: 10,
          },
          {
            id: 2,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/avai-disc-meal4.png"),
            price: 10,
          },
          {
            id: 3,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/avai-disc-meal4.png"),
            price: 10,
          },
        ],
      },
      {
        id: 4,
        image: require("../assets/images/avai-disc-meal2.png"),
        name: "Papa Johns",
        description: "Hot and Spicy Pizzas",
        lng: 38.2145602,
        lat: -85.5324269,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/sea food.jpeg"),
            price: 10,
          },
          {
            id: 2,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/sea food.jpeg"),
            price: 10,
          },
          {
            id: 3,
            name: "Pizza",
            description: "Cheezy garlic pizzas",
            image: require("../assets/images/sea food.jpeg"),
            price: 10,
          },
        ],
      },
    ],
  },
];
